version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: db_tenpo
      POSTGRES_USER: ojacome
      POSTGRES_PASSWORD: 12345678
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ojacome -d db_tenpo"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: api-tenpo
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/db_tenpo
      SPRING_DATASOURCE_USERNAME: ojacome
      SPRING_DATASOURCE_PASSWORD: 12345678
      CACHE_PERCENTAGE_EXPIRE_MINUTES: 30
      EXTERNAL_SERVICE_URL: https://b228a110-1857-4572-9f1a-7eb59c1e2058.mock.pstmn.io/api/percentage
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres_data:
